// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AStar: typeof import("./src/components/AStar.vue")["default"];
    ControlWindow: typeof import("./src/components/ControlWindow.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInputNumber: typeof import("element-plus/es")["ElInputNumber"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    Grid: typeof import("./src/components/Grid.vue")["default"];
    KeyboardShortcutsHelp: typeof import("./src/components/KeyboardShortcutsHelp.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TileMenu: typeof import("./src/components/TileMenu.vue")["default"];
  }
}
